### PR TITLE
auto orientation

### PR DESCRIPTION
**Pull request by laraben**
Get the orientation of the page automatically.

Like this you can easily merge docs with different orientations.
System check the orientation of the page and use this.

### CODE REVIEW

**Comment by dhcmega** [comment]
Hi, I think this modification forces the same orientation for the whole file, doesn't it?
I have a file with mixed landscape and portrait, and the P is applied to all pages.
Thanks

**Comment by dhcmega** [comment]
This is working for me, is there any reason not to change it like this?

```php
    protected function doMerge($orientation, $duplexSafe) {

        if ($this->aFiles->count() == 0) {
            throw new \Exception("No PDFs to merge.");
        }

        $oFPDI = $this->oFPDI;

        $this->aFiles->each(function($file) use($oFPDI, $orientation, $duplexSafe){
            $file['orientation'] = is_null($file['orientation'])?$orientation:$file['orientation'];
            $count = $oFPDI->setSourceFile(StreamReader::createByString(file_get_contents($file['name'])));
            if ($file['pages'] == 'all') {

                for ($i = 1; $i <= $count; $i++) {
                    $template   = $oFPDI->importPage($i);
                    $size = $oFPDI->getTemplateSize($template);
                    $autoOrientation = $size['orientation'];

                    $oFPDI->AddPage($autoOrientation, [$size['width'], $size['height']]);
                    $oFPDI->useTemplate($template);
                }
            } else {
                foreach ($file['pages'] as $page) {
                    if (!$template = $oFPDI->importPage($page)) {
                        throw new \Exception("Could not load page '$page' in PDF '".$file['name']."'. Check that the page exists.");
                    }
                    $size = $oFPDI->getTemplateSize($template);
                    $autoOrientation = $size['orientation'];

                    $oFPDI->AddPage($autoOrientation, [$size['width'], $size['height']]);
                    $oFPDI->useTemplate($template);
                }
            }

            if ($duplexSafe && $oFPDI->page % 2) {
                $oFPDI->AddPage($file['orientation'], [$size['width'], $size['height']]);
            }
        });
    }
```

**Comment by giagara** [comment]
Any news about this?

**Comment by dhcmega** [comment]
I just forked it.

**Pull request merged**
